import { useState } from "react";
import { useNavigate } from "react-router-dom";

import Card from "../components/common/Card";
import Button from "../components/common/Button";
import Checkbox from "../components/common/Checkbox";

import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

export default function ConsentPage() {
  const [accepted, setAccepted] = useState(false);

  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[#08070A] flex flex-col">
      <Header />

      <main className="flex-1 px-4 py-6 sm:px-6 md:px-8 lg:px-10">
        <div className="mx-auto max-w-5xl">
        <Card className="bg-[#131118] border border-[#232129] shadow-[0_0_40px_rgba(147,205,12,0.08)] p-6 sm:p-8 md:p-10">

            <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-white">
            Welcome
          </h1>

          <h2 className="mt-2 text-lg sm:text-xl text-[#93CD0C]">
            AI Interview Coach Demo
          </h2>

          <div className="mt-8 space-y-5 text-sm sm:text-base leading-7 sm:leading-8 text-gray-300">

            <p>
              Thank you for participating in the Deloitte AI Interview Coach demonstration.
            </p>

            <p>
              During this experience you will upload your CV so our AI can analyse
              your skills, education, experience and projects to recommend suitable
              career paths and generate personalised interview questions.
            </p>

            <p>
              Your personal information will be used only for this demonstration.
              Your data will <strong>not</strong> be used to train any Large Language
              Model (LLM) or any other AI model.
            </p>

            <p>
              All personal information is processed in accordance with the
              <strong> Protection of Personal Information Act (POPIA)</strong>.
            </p>

            <p>
              This demonstration is intended for educational and career guidance
              purposes only. It does not constitute an offer of employment,
              recruitment decision or guarantee of employment.
            </p>

            <p>
              Deloitte, Amazon Web Services and any demonstration partners shall
              not be held liable for decisions made based on recommendations
              generated by this application.
            </p>

          </div>

          <div className="mt-8">
            <Checkbox
              checked={accepted}
              onChange={setAccepted}
              label="I have read, understood and agree to the Privacy Notice and Consent Statement."
            />
          </div>

          <div className="mt-10 grid gap-4 sm:grid-cols-2">

            <Button
              onClick={() => navigate("/student-upload")}
              disabled={!accepted}
            >
              I Agree
            </Button>

            <Button
              onClick={() => navigate("/declined")}
            >
              I Do Not Agree
            </Button>

          </div>

        </Card>
        </div>
      </main>

      <Footer />
    </div>
  );
}