import { useState } from "react";
import { useNavigate } from "react-router-dom";

import Card from "../components/common/Card";
import Button from "../components/common/Button";
import Checkbox from "../components/common/Checkbox";

import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

export default function ConsentPage() {
  const [accepted, setAccepted] = useState(false);

  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[#08070A] flex flex-col">
      <Header />

      <main className="flex-1 flex items-center justify-center px-6 py-10">
        <Card className="max-w-4xl w-full bg-[#131118] border border-[#232129] shadow-[0_0_40px_rgba(147,205,12,0.08)]">

          <h1 className="text-4xl font-bold text-white mb-2">
            Welcome
          </h1>

          <h2 className="text-[#93CD0C] mb-8 text-xl">
            AI Interview Coach Demo
          </h2>

          <div className="space-y-5 text-gray-300 leading-7">

            <p>
              Thank you for participating in the Deloitte AI Interview Coach demonstration.
            </p>

            <p>
              During this experience you will upload your CV so our AI can analyse
              your skills, education, experience and projects to recommend suitable
              career paths and generate personalised interview questions.
            </p>

            <p>
              Your personal information will be used only for this demonstration.
              Your data will <strong>not</strong> be used to train any Large Language
              Model (LLM) or any other AI model.
            </p>

            <p>
              All personal information is processed in accordance with the
              <strong> Protection of Personal Information Act (POPIA)</strong>.
            </p>

            <p>
              This demonstration is intended for educational and career guidance
              purposes only. It does not constitute an offer of employment,
              recruitment decision or guarantee of employment.
            </p>

            <p>
              Deloitte, Amazon Web Services and any demonstration partners shall
              not be held liable for decisions made based on recommendations
              generated by this application.
            </p>

          </div>

          <div className="mt-8">
            <Checkbox
              checked={accepted}
              onChange={setAccepted}
              label="I have read, understood and agree to the Privacy Notice and Consent Statement."
            />
          </div>

          <div className="mt-10 flex flex-col gap-4 sm:flex-row">

            <Button
              onClick={() => navigate("/home")}
              disabled={!accepted}
            >
              I Agree
            </Button>

            <Button
              onClick={() => navigate("/declined")}
            >
              I Do Not Agree
            </Button>

          </div>

        </Card>
      </main>

      <Footer />
    </div>
  );
}